spring:
  datasource:
    url: jdbc:h2:file:./data/myrpg;AUTO_SERVER=TRUE
    username: sa
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

server:
  port: 8083
