server:
  port: 8082

logging:
  level:
    root: info

spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  profiles:
    active: local
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        "[default_schema]": admin
        "[dialect]": org.hibernate.dialect.OracleDialect
  thymeleaf:
    cache: false
