spring:
  datasource:
    url: jdbc:oracle:thin:@i38zv6g9lrf9fi84_high?TNS_ADMIN=/Users/gony/oracle_cloud/db/Wallet_I38ZV6G9LRF9FI84
    username: admin
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      data-source-properties:
        oracle.net.tns_admin: /Users/gony/oracle_cloud/db/Wallet_I38ZV6G9LRF9FI84
