spring:
  datasource:
    url: jdbc:oracle:thin:@I38ZV6G9LRF9FI84_high?TNS_ADMIN=/Users/gony/oracle_cloud/db/Wallet_I38ZV6G9LRF9FI84
    username: admin
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
      